### PR TITLE
Init git, github, and release/regex from k/release

### PR DESCRIPTION
**Pull request by justaugustus**
As part of migrating `gh2gcs` to the CIP repo (https://github.com/kubernetes-sigs/k8s-container-image-promoter/pull/423), we need to detangle a few inevitable import cycles between repos. Here we:

- Migrate k/release/pkg/{git,github,release/regex} (76deea6)
- git,github,regex: Update import paths 
- generated: Run `go mod tidy`

(Similar motivations as https://github.com/kubernetes-sigs/release-sdk/pull/2.)

/assign @puerco @cpanato @Verolop @ameukam 
cc: @kubernetes-sigs/release-engineering

### CODE REVIEW

**Comment by justaugustus** [comment]
/hold for https://kubernetes.slack.com/archives/CJH2GBF7Y/p1631554684074900?thread_ts=1631554156.074500&cid=CJH2GBF7Y

@puerco
> I still think git + github should go to release-utils. Are you sure it is not double+ work to have them in sdk first?

@justaugustus
> @puerco — checking again, github is safe to go to release-utils instead, but git has Kubernetes-specific references, so it should go to release-sdk

@puerco
> SGTM, Once we strip out the calls to the git binary in the git package, we can remove the k8s-specific stuff

**Comment by justaugustus** [comment]
/hold cancel
(@puerco's feedback has been addressed.)

**Comment by puerco** [comment]
Awesome, opened a follow up issue to address the calls to `git`:  https://github.com/kubernetes-sigs/release-sdk/issues/4

/lgtm

**Comment by justaugustus** [comment]
/hold cancel
(ref: https://kubernetes.slack.com/archives/CJH2GBF7Y/p1631557597076000?thread_ts=1631554156.074500&cid=CJH2GBF7Y)

@justaugustus
> @puerco — actually, I stand by the original assessment (because of github importing git)

@justaugustus
> Let’s do the initial migration to release-sdk and then pull out the git stuff in a follow-up

@puerco
> ok :thumbsup:

@justaugustus
> (I’d just prefer not to have any refactors masked by the migration commits)

@puerco
> yeah makes sense

@justaugustus
> also, it looks like it might be really simple, but I’ve made the mistake of assuming that before :upside_down_face:

**Comment by puerco** [comment]
Due to the import cycle, we will address the move of the `github` package in a follow-up
/lgtm

**Pull request merged**
