### PR TITLE
Add `sign` package skeleton

### PR DESCRIPTION
**Pull request by saschagrunert**
This commit adds a basic sign skeleton for further development purposes.
It also outlines the API as well as a verbose logging option.

cc @kubernetes-sigs/release-engineering 

Refers to https://github.com/kubernetes/release/issues/2383

### CODE REVIEW

**Review by cpanato — APPROVED** [review]
/lgtm
thanks!

**Comment by puerco** [comment]
Oooh awesome!!

**Comment by puerco** [comment]
One question about the interface, looking at the sign pkg, there are three methods:
`Sign`, `UploadBlob`, `Verify`.

Are you thinking to have one generic `Sign()` method to sign everything (images, blobs, attestations, etc) controlled via the options? Or should we rather have `SignImage()`, `SignAttestation()`, etc?

**Comment by saschagrunert** [comment]
> One question about the interface, looking at the sign pkg, there are three methods: `Sign`, `UploadBlob`, `Verify`.
> 
> Are you thinking to have one generic `Sign()` method to sign everything (images, blobs, attestations, etc) controlled via the options? Or should we rather have `SignImage()`, `SignAttestation()`, etc?
> 
> (I get we are building the MVP now, but for the next iteration after that)

Yeah my intention was to make it work universally. Now that I'm thinking of, It may be better to distinguish files from image references. How about having:

- `SignImage(reference string)`
- `SignFile(path string)`

**Comment by puerco** [comment]
I think it is better too. There is some logic we have to wrap for each kind, for example adding a wrapper to attestations. We can have them separate and explore a one for all method later :)

**Pull request merged**
